<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('roles', function (Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->string('label'); $t->timestamps(); });
        Schema::create('permissions', function (Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->string('label'); $t->timestamps(); });
        Schema::create('role_user', function (Blueprint $t) { $t->foreignId('role_id')->constrained()->cascadeOnDelete(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->primary(['role_id','user_id']); });
        Schema::create('permission_role', function (Blueprint $t) { $t->foreignId('permission_id')->constrained()->cascadeOnDelete(); $t->foreignId('role_id')->constrained()->cascadeOnDelete(); $t->primary(['permission_id','role_id']); });
        Schema::create('warehouses', function (Blueprint $t) { $t->id(); $t->string('code')->unique(); $t->string('name'); $t->text('address')->nullable(); $t->foreignId('manager_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('phone')->nullable(); $t->decimal('capacity',16,3)->nullable(); $t->string('status')->default('active')->index(); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('user_warehouse', function (Blueprint $t) { $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->foreignId('warehouse_id')->constrained()->cascadeOnDelete(); $t->primary(['user_id','warehouse_id']); });
        Schema::create('categories', function (Blueprint $t) { $t->id(); $t->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete(); $t->string('name'); $t->string('slug')->unique(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('brands', function (Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('units', function (Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->string('symbol',20); $t->unsignedTinyInteger('precision')->default(0); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('suppliers', function (Blueprint $t) { $t->id(); $t->string('code')->unique(); $t->string('company_name')->index(); $t->string('contact_person')->nullable(); $t->string('phone')->nullable(); $t->string('email')->nullable(); $t->text('address')->nullable(); $t->string('payment_terms')->nullable(); $t->text('notes')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->timestamps(); });
        Schema::create('products', function (Blueprint $t) { $t->id(); $t->string('sku')->unique(); $t->string('product_code')->unique(); $t->string('barcode')->nullable()->unique(); $t->string('name')->index(); $t->text('description')->nullable(); $t->foreignId('category_id')->constrained()->restrictOnDelete(); $t->foreignId('brand_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('unit_id')->constrained()->restrictOnDelete(); $t->decimal('purchase_cost',16,2)->default(0); $t->decimal('selling_price',16,2)->default(0); $t->decimal('minimum_stock',16,3)->default(0); $t->decimal('reorder_quantity',16,3)->default(0); $t->string('image_path')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->boolean('is_discontinued')->default(false); $t->timestamps(); $t->softDeletes(); });
        Schema::create('inventories', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->restrictOnDelete(); $t->foreignId('warehouse_id')->constrained()->restrictOnDelete(); $t->decimal('on_hand',16,3)->default(0); $t->decimal('reserved',16,3)->default(0); $t->timestamps(); $t->unique(['product_id','warehouse_id']); });
        Schema::create('stock_movements', function (Blueprint $t) { $t->id(); $t->string('reference_number')->index(); $t->foreignId('product_id')->constrained()->restrictOnDelete(); $t->foreignId('warehouse_id')->constrained()->restrictOnDelete(); $t->string('type')->index(); $t->decimal('quantity',16,3); $t->decimal('quantity_before',16,3); $t->decimal('quantity_after',16,3); $t->nullableMorphs('reference'); $t->string('reason')->nullable(); $t->text('notes')->nullable(); $t->foreignId('performed_by')->constrained('users')->restrictOnDelete(); $t->timestamps(); $t->index(['warehouse_id','created_at']); });
        Schema::create('purchase_orders', function (Blueprint $t) { $t->id(); $t->string('number')->unique(); $t->foreignId('supplier_id')->constrained()->restrictOnDelete(); $t->foreignId('warehouse_id')->constrained()->restrictOnDelete(); $t->date('order_date'); $t->date('expected_delivery_date')->nullable(); $t->string('status')->default('draft')->index(); $t->decimal('subtotal',16,2)->default(0); $t->decimal('discount',16,2)->default(0); $t->decimal('tax',16,2)->default(0); $t->decimal('total',16,2)->default(0); $t->text('notes')->nullable(); $t->foreignId('created_by')->constrained('users'); $t->foreignId('approved_by')->nullable()->constrained('users'); $t->timestamp('approved_at')->nullable(); $t->timestamps(); });
        Schema::create('purchase_order_items', function (Blueprint $t) { $t->id(); $t->foreignId('purchase_order_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained()->restrictOnDelete(); $t->decimal('quantity',16,3); $t->decimal('received_quantity',16,3)->default(0); $t->decimal('unit_price',16,2); $t->decimal('line_total',16,2); $t->unique(['purchase_order_id','product_id']); });
        Schema::create('goods_receipts', function (Blueprint $t) { $t->id(); $t->string('number')->unique(); $t->foreignId('purchase_order_id')->constrained()->restrictOnDelete(); $t->foreignId('received_by')->constrained('users'); $t->timestamp('received_at'); $t->string('document_path')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('goods_receipt_items', function (Blueprint $t) { $t->id(); $t->foreignId('goods_receipt_id')->constrained()->cascadeOnDelete(); $t->foreignId('purchase_order_item_id')->constrained()->restrictOnDelete(); $t->decimal('quantity',16,3); });
        Schema::create('transfers', function (Blueprint $t) { $t->id(); $t->string('number')->unique(); $t->foreignId('source_warehouse_id')->constrained('warehouses'); $t->foreignId('destination_warehouse_id')->constrained('warehouses'); $t->string('status')->default('draft')->index(); $t->foreignId('requested_by')->constrained('users'); $t->foreignId('approved_by')->nullable()->constrained('users'); $t->foreignId('shipped_by')->nullable()->constrained('users'); $t->foreignId('received_by')->nullable()->constrained('users'); $t->timestamp('approved_at')->nullable(); $t->timestamp('shipped_at')->nullable(); $t->timestamp('received_at')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('transfer_items', function (Blueprint $t) { $t->id(); $t->foreignId('transfer_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained(); $t->decimal('quantity',16,3); $t->unique(['transfer_id','product_id']); });
        Schema::create('stock_adjustments', function (Blueprint $t) { $t->id(); $t->string('number')->unique(); $t->foreignId('warehouse_id')->constrained(); $t->foreignId('product_id')->constrained(); $t->decimal('system_quantity',16,3); $t->decimal('counted_quantity',16,3); $t->decimal('difference',16,3); $t->string('reason'); $t->text('notes')->nullable(); $t->string('status')->default('pending')->index(); $t->foreignId('requested_by')->constrained('users'); $t->foreignId('approved_by')->nullable()->constrained('users'); $t->timestamp('approved_at')->nullable(); $t->timestamps(); });
        Schema::create('sales_orders', function (Blueprint $t) { $t->id(); $t->string('number')->unique(); $t->string('customer'); $t->foreignId('warehouse_id')->constrained(); $t->string('status')->default('draft')->index(); $t->decimal('total',16,2)->default(0); $t->text('notes')->nullable(); $t->foreignId('created_by')->constrained('users'); $t->timestamps(); });
        Schema::create('sales_order_items', function (Blueprint $t) { $t->id(); $t->foreignId('sales_order_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained(); $t->decimal('quantity',16,3); $t->decimal('unit_price',16,2); $t->unique(['sales_order_id','product_id']); });
        Schema::create('stock_alerts', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained(); $t->foreignId('warehouse_id')->constrained(); $t->string('level')->index(); $t->decimal('quantity',16,3); $t->timestamp('resolved_at')->nullable(); $t->timestamps(); $t->index(['product_id','warehouse_id','resolved_at']); });
        Schema::create('audit_logs', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('action')->index(); $t->nullableMorphs('auditable'); $t->json('old_values')->nullable(); $t->json('new_values')->nullable(); $t->ipAddress('ip_address')->nullable(); $t->timestamps(); });
        Schema::create('settings', function (Blueprint $t) { $t->id(); $t->string('key')->unique(); $t->text('value')->nullable(); $t->string('type')->default('string'); $t->boolean('is_public')->default(false); $t->timestamps(); });
        Schema::create('notifications', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('type'); $t->morphs('notifiable'); $t->text('data'); $t->timestamp('read_at')->nullable(); $t->timestamps(); });
    }

    public function down(): void
    {
        foreach (['notifications','settings','audit_logs','stock_alerts','sales_order_items','sales_orders','stock_adjustments','transfer_items','transfers','goods_receipt_items','goods_receipts','purchase_order_items','purchase_orders','stock_movements','inventories','products','suppliers','units','brands','categories','user_warehouse','warehouses','permission_role','role_user','permissions','roles'] as $table) Schema::dropIfExists($table);
    }
};
