import { useCallback, useEffect, useState } from 'react'
import { Download, FileBarChart } from 'lucide-react'
import { api } from '../api/client'
import { DataTable } from '../components/DataTable'
const reports=[['inventory','Inventory summary'],['low-stock','Low & out of stock'],['movements','Stock movements'],['purchase-orders','Purchase orders'],['supplier-purchases','Supplier purchases'],['transfers','Warehouse transfers'],['adjustments','Stock adjustments'],['valuation','Inventory valuation']]
export function ReportCenter(){
 const[type,setType]=useState('inventory');const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[filters,setFilters]=useState({date_from:'',date_to:'',warehouse_id:'',status:''})
 const run=useCallback(async(params={})=>{setLoading(true);try{const r=await api.get(`/reports/${type}`,{params});setRows(r.data.data||[])}finally{setLoading(false)}},[type])
 useEffect(()=>{api.get(`/reports/${type}`).then(r=>setRows(r.data.data||[])).finally(()=>setLoading(false))},[type])
 const keys=rows.length?Object.keys(rows[0]).filter(k=>!['id','created_at','updated_at'].includes(k)&&typeof rows[0][k]!=='object').slice(0,8):[];const cols=keys.map(k=>({key:k,label:k.replaceAll('_',' '),render:v=>typeof v==='boolean'?(v?'Yes':'No'):v}))
 return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold">Reports</h2><p className="text-sm text-slate-500">Operational reports with server-side filters and CSV export.</p></div>{type==='inventory'&&<a className="btn-primary" href={`${import.meta.env.VITE_API_URL||'http://localhost:8000/api/v1'}/reports/inventory?csv=1`}><Download size={16}/>Export CSV</a>}</div><div className="card p-4"><div className="flex gap-2 overflow-x-auto pb-4">{reports.map(([key,label])=><button key={key} onClick={()=>setType(key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold ${type===key?'bg-[#1d5b3a] text-white':'bg-slate-100 text-slate-600'}`}>{label}</button>)}</div><div className="grid gap-3 border-t pt-4 sm:grid-cols-2 lg:grid-cols-5"><input type="date" className="input" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/><input type="date" className="input" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/><input className="input" placeholder="Warehouse ID" value={filters.warehouse_id} onChange={e=>setFilters({...filters,warehouse_id:e.target.value})}/><input className="input" placeholder="Status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}/><button className="btn-secondary" onClick={()=>run(filters)}><FileBarChart size={16}/>Run report</button></div></div><DataTable columns={cols.length?cols:[{key:'message',label:'Result'}]} rows={rows} loading={loading}/></div>
}
