<?php

use App\Http\Controllers\Api\V1\AdminController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BarcodeController;
use App\Http\Controllers\Api\V1\CatalogController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\FileController;
use App\Http\Controllers\Api\V1\InventoryController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\SystemController;
use App\Http\Controllers\Api\V1\WorkflowController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:6,1');
    Route::post('/auth/forgot-password', [AuthController::class, 'forgot'])->middleware('throttle:6,1');
    Route::middleware(['auth:sanctum', 'active'])->group(function () {
        Route::get('/auth/user', [AuthController::class, 'user']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::put('/auth/password', [AuthController::class, 'changePassword']);
        Route::get('/dashboard', DashboardController::class);
        Route::get('/notifications', [SystemController::class, 'notifications']);
        Route::post('/notifications/read-all', [SystemController::class, 'readAllNotifications']);
        Route::post('/notifications/{id}/read', [SystemController::class, 'readNotification']);
        Route::get('/settings', [SystemController::class, 'settings'])->middleware('permission:settings.manage');
        Route::put('/settings', [SystemController::class, 'updateSettings'])->middleware('permission:settings.manage');
        Route::get('/audit-logs', [SystemController::class, 'audits'])->middleware('permission:audit.view');
        Route::get('/users', [AdminController::class, 'users'])->middleware('permission:users.manage');
        Route::post('/users', [AdminController::class, 'storeUser'])->middleware('permission:users.manage');
        Route::get('/users/{user}', [AdminController::class, 'user'])->middleware('permission:users.manage');
        Route::put('/users/{user}', [AdminController::class, 'updateUser'])->middleware('permission:users.manage');
        Route::get('/roles', [AdminController::class, 'roles'])->middleware('permission:users.manage');
        Route::post('/roles', [AdminController::class, 'storeRole'])->middleware('permission:users.manage');
        Route::put('/roles/{role}', [AdminController::class, 'updateRole'])->middleware('permission:users.manage');
        Route::get('/permissions', [AdminController::class, 'permissions'])->middleware('permission:users.manage');
        Route::middleware('permission:reports.view')->prefix('reports')->group(function () {
            Route::get('/inventory', [ReportController::class, 'inventory']);
            Route::get('/movements', [ReportController::class, 'movements']);
            Route::get('/low-stock', [ReportController::class, 'lowStock']);
            Route::get('/purchase-orders', [ReportController::class, 'purchaseOrders']);
            Route::get('/supplier-purchases', [ReportController::class, 'supplierPurchases']);
            Route::get('/transfers', [ReportController::class, 'transfers']);
            Route::get('/adjustments', [ReportController::class, 'adjustments']);
            Route::get('/valuation', [ReportController::class, 'valuation']);
        });
        Route::get('/inventory', [InventoryController::class, 'index']);
        Route::get('/movements', [InventoryController::class, 'movements']);
        Route::post('/inventory/manual', [InventoryController::class, 'manual'])->middleware('permission:inventory.adjust');
        Route::post('/products/{product}/image', [FileController::class, 'productImage'])->middleware('permission:master.manage');
        Route::post('/documents', [FileController::class, 'document']);
        Route::get('/products/{product}/barcode', BarcodeController::class);
        Route::get('/purchase-orders', [WorkflowController::class, 'purchaseOrders']);
        Route::post('/purchase-orders', [WorkflowController::class, 'createPurchaseOrder'])->middleware('permission:purchases.manage');
        Route::get('/purchase-orders/{order}', [WorkflowController::class, 'purchaseOrder']);
        Route::post('/purchase-orders/{order}/submit', [WorkflowController::class, 'submitPurchaseOrder'])->middleware('permission:purchases.manage');
        Route::post('/purchase-orders/{order}/approve', [WorkflowController::class, 'approvePurchaseOrder'])->middleware('permission:purchases.approve');
        Route::post('/purchase-orders/{order}/receive', [WorkflowController::class, 'receive'])->middleware('permission:purchases.receive');
        Route::get('/transfers', [WorkflowController::class, 'transfers']);
        Route::post('/transfers', [WorkflowController::class, 'createTransfer'])->middleware('permission:transfers.manage');
        Route::get('/transfers/{transfer}', [WorkflowController::class, 'transfer']);
        Route::post('/transfers/{transfer}/{action}', [WorkflowController::class, 'transferAction'])->whereIn('action', ['approve', 'ship', 'receive'])->middleware('permission:transfers.manage');
        Route::get('/sales-orders', [WorkflowController::class, 'salesOrders']);
        Route::post('/sales-orders', [WorkflowController::class, 'createSalesOrder'])->middleware('permission:sales.manage');
        Route::get('/sales-orders/{order}', [WorkflowController::class, 'salesOrder']);
        Route::post('/sales-orders/{order}/{action}', [WorkflowController::class, 'salesAction'])->whereIn('action', ['reserve', 'dispatch'])->middleware('permission:sales.manage');
        Route::get('/adjustments', [WorkflowController::class, 'adjustments']);
        Route::post('/adjustments', [WorkflowController::class, 'createAdjustment'])->middleware('permission:inventory.adjust');
        Route::get('/adjustments/{adjustment}', [WorkflowController::class, 'adjustment']);
        Route::post('/adjustments/{adjustment}/approve', [WorkflowController::class, 'approveAdjustment'])->middleware('permission:inventory.adjust');
        Route::get('/{resource}', [CatalogController::class, 'index'])->whereIn('resource', ['products', 'categories', 'brands', 'units', 'suppliers', 'warehouses']);
        Route::post('/{resource}', [CatalogController::class, 'store'])->whereIn('resource', ['products', 'categories', 'brands', 'units', 'suppliers', 'warehouses'])->middleware('permission:master.manage');
        Route::get('/{resource}/{id}', [CatalogController::class, 'show'])->whereIn('resource', ['products', 'categories', 'brands', 'units', 'suppliers', 'warehouses']);
        Route::put('/{resource}/{id}',[CatalogController::class, 'update'])->whereIn('resource',['products', 'categories', 'brands', 'units', 'suppliers', 'warehouses'])->middleware('permission:master.manage');
    });
});
